name: Shrine
description: Learn how to use Material for structure and layout.

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.6

  flutter_webview_plugin: ^0.3.10+2

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/images/0-0.jpg
    - assets/images/1-0.jpg
    - assets/images/2-0.jpg
    - assets/images/3-0.jpg
    - assets/images/4-0.jpg
    - assets/images/5-0.jpg
    - assets/images/6-0.jpg
